#!/usr/bin/env python
# -*- coding:utf-8 -*-
# nagexiucai.com


from wx.lib.embeddedimage import PyEmbeddedImage

ICON = PyEmbeddedImage(
    "AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAT/AQYG/wIICP8FDQ7/CBIU/wwWG/8SHiT/FiQs/xssNf8WJiz/ITM8/xwsNv8ZKDD/EiMt/wg"
    "WG/8BDA7/AQUE/wEGBv8FDAz/CRMW/wwWGv8QGyH/FiQs/x4uOf8qPUv/MERU/ys/TP8rPk3/JzxK/yI0Qv8RISr/BRMU/wAFBP8FDAz/CBIS/woTGP8TICf/GCUt/xopMv8eMDr/KT5N/y9FUv89U2T/PVhs/yc"
    "7Sf8dMUD/Gi46/wYVF/8BBgf/BAsL/wYQEf8QHSH/ER8k/xcmK/8dLjX/KD1J/yo9Sv8zSVr/QVpr/0RgeP9Qcov/NEte/x8zPv8PICb/AQQE/wUMDv8KExf/EB0g/xEeIf8fLzX/HS44/zFGUf8sPkr/QFls/zp"
    "PXv9La4T/RmV8/01tg/8wSVr/ESIm/wIEBf8ECgv/DBca/w4aHf8PGx7/IDA5/xssNP8fMTj/KTpG/0Faa/9JZn3/TnCL/1J0jv8tR1r/IztJ/xosNP8AAQH/BAkL/wYPE/8LFhr/Dx0g/x0tOP8cLDf/Fict/xw"
    "rN/82TF//Plx0/1Byjf9FZn//WXyN/0Fgcf8dMTj/AQMD/wMHCf8FDRD/ChUZ/w8cI/8RHiX/FCIn/xAeJP8YJy//JjxL/zxadP9DZYH/VnyW/12Gm/9EZ3f/Gi82/wABAf8CBQb/BQwP/wgRFv8LFx//EiAp/xI"
    "eKP8VIzD/FiUt/yI4Sv8vTGb/QWSB/1F4lP9KcIT/NVRi/xcqMP8BAQH/AgUG/wMMDv8GERX/BxIZ/wwXHv8XJDH/FiMw/xYkMv8iN0j/KERe/zxfe/9BZoH/P2J0/zpYaP8QIST/AAAA/wMHCP8ECg7/BhAV/wg"
    "RGP8OGiX/DBgh/xQjM/8PGiP/Giw8/yZBW/89X3r/RWmD/0pvg/8uTVn/EiIk/wABAf8AAgL/AwgK/wQOEf8GDxT/ChYg/xMhMP8WKD7/GStB/x84Tv8qRl7/RGeD/0Vnfv80VGb/LUdU/wkVFv8AAAD/AQIC/wI"
    "GBv8CCAv/Bg4T/wgRGv8HFB3/EB4s/xQoOP8lP1b/JT5V/zpXcv82VWz/Ollu/x4zPv8CCQn/AAEA/wAAAP8CBQb/AwgI/wQKDv8HEBr/BhEX/w4ZI/8XKDn/HzNH/y1EYP8tSF//KEFV/yI6Sv8NHCH/AAIC/wA"
    "BAP8AAAD/AAAA/wIFBv8CCAv/AwsQ/wUMEv8HERr/FCAu/xgnOf8WJjn/JTpO/xQoNv8WKTT/BhMW/wABAf8BAQD/AAAA/wAAAP8BAQH/AQUG/wEFB/8BBQf/BAkO/wcNE/8LExz/Dxgj/woWH/8PHCX/CBMZ/wI"
    "JCv8AAQH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
)
